test:
  name: Ticket Registration Benchmark
  description: Benchmark for RegisterPassenger function
  workers:
    type: local
    number: 2
  rounds:
    - label: Register Passenger
      description: Test the throughput of registering new passengers
      txNumber: 2000
      rateControl:
        type: maximum-rate
        opts:
          tps: 1000
      workload:
        module: workload.js
    - label: Buy Ticket
      description: Test the throughput of buying tickets (high contention)
      txNumber: 50
      rateControl:
        type: maximum-rate
        opts:
          tps: 500
      workload:
        module: workload-buyTicket.js